language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - pip --version
  - pip install -r test-requirements.txt
  - pip install pep8 
before_script:
  - pep8 -v *.py VHostScan/
script:
  - pytest
