--- 
:self:
  :name: Self Hosted
:other:
  :name: Other / Self Hosted
:none:
  :name: None
:softlayer: 
  :name: SoftLayer
  :dba: 
  - softlayer corporate c
  - softlayer technologies inc.
  - softlayer technologies
  - softlayer.com
  - theplanet.com internet services
  - theplanet.com internet services, inc.
:netsol: 
  :name: Network Solutions
  :dba: 
  - network solutions, llc.
  - network solutions llc
  - network solutions l.l.c.
:everydns: 
  :name: EveryDNS.net
  :dba: 
  - everydns.net
:datapipe: 
  :name: DataPipe
  :dba: 
  - datapipe, inc.
  - datapipe.net
:vzw_biz: 
  :name: Verizon (Cybertrust)
  :dba: 
  - gte corporation
:registercom: 
  :name: Register.com
  :dba: 
  - register.com, inc.
:markmonitor: 
  :name: MarkMonitor
  :dba: 
  - markmonitor inc.
  - markmonitor.com
:dyn_inc: 
  :name: Dyn Inc
  :dba: 
  - mailhop.org
  - mydyndns.org
  - dynect.net
  - dynamic network services, inc
  - dynamic network services, inc.
:amazon: 
  :name: Amazon
  :dba: 
  - amazon.com
  - amazon.com, inc.
  - awsdns-00.co.uk
  - awsdns-00.com
  - awsdns-00.net
  - awsdns-00.org
  - awsdns-01.co.uk
  - awsdns-01.com
  - awsdns-01.net
  - awsdns-01.org
  - awsdns-02.co.uk
  - awsdns-02.com
  - awsdns-02.net
  - awsdns-02.org
  - awsdns-03.co.uk
  - awsdns-03.com
  - awsdns-03.net
  - awsdns-03.org
  - awsdns-04.co.uk
  - awsdns-04.com
  - awsdns-04.net
  - awsdns-04.org
  - awsdns-05.co.uk
  - awsdns-05.com
  - awsdns-05.net
  - awsdns-05.org
  - awsdns-06.co.uk
  - awsdns-06.com
  - awsdns-06.net
  - awsdns-06.org
  - awsdns-07.co.uk
  - awsdns-07.com
  - awsdns-07.net
  - awsdns-07.org
  - awsdns-08.co.uk
  - awsdns-08.com
  - awsdns-08.net
  - awsdns-08.org
  - awsdns-09.co.uk
  - awsdns-09.com
  - awsdns-09.net
  - awsdns-09.org
  - awsdns-10.co.uk
  - awsdns-10.com
  - awsdns-10.net
  - awsdns-10.org
  - awsdns-11.co.uk
  - awsdns-11.com
  - awsdns-11.net
  - awsdns-11.org
  - awsdns-12.co.uk
  - awsdns-12.com
  - awsdns-12.net
  - awsdns-12.org
  - awsdns-13.co.uk
  - awsdns-13.com
  - awsdns-13.net
  - awsdns-13.org
  - awsdns-14.co.uk
  - awsdns-14.com
  - awsdns-14.net
  - awsdns-14.org
  - awsdns-15.co.uk
  - awsdns-15.com
  - awsdns-15.net
  - awsdns-15.org
  - awsdns-16.co.uk
  - awsdns-16.com
  - awsdns-16.net
  - awsdns-16.org
  - awsdns-17.co.uk
  - awsdns-17.com
  - awsdns-17.net
  - awsdns-17.org
  - awsdns-18.co.uk
  - awsdns-18.com
  - awsdns-18.net
  - awsdns-18.org
  - awsdns-19.co.uk
  - awsdns-19.com
  - awsdns-19.net
  - awsdns-19.org
  - awsdns-20.co.uk
  - awsdns-20.com
  - awsdns-20.net
  - awsdns-20.org
  - awsdns-21.co.uk
  - awsdns-21.com
  - awsdns-21.net
  - awsdns-21.org
  - awsdns-22.co.uk
  - awsdns-22.com
  - awsdns-22.net
  - awsdns-22.org
  - awsdns-23.co.uk
  - awsdns-23.com
  - awsdns-23.net
  - awsdns-23.org
  - awsdns-24.co.uk
  - awsdns-24.com
  - awsdns-24.net
  - awsdns-24.org
  - awsdns-25.co.uk
  - awsdns-25.com
  - awsdns-25.net
  - awsdns-25.org
  - awsdns-26.co.uk
  - awsdns-26.com
  - awsdns-26.net
  - awsdns-26.org
  - awsdns-27.co.uk
  - awsdns-27.com
  - awsdns-27.net
  - awsdns-27.org
  - awsdns-28.co.uk
  - awsdns-28.com
  - awsdns-28.net
  - awsdns-28.org
  - awsdns-29.co.uk
  - awsdns-29.com
  - awsdns-29.net
  - awsdns-29.org
  - awsdns-30.co.uk
  - awsdns-30.com
  - awsdns-30.net
  - awsdns-30.org
  - awsdns-31.co.uk
  - awsdns-31.com
  - awsdns-31.net
  - awsdns-31.org
  - awsdns-32.co.uk
  - awsdns-32.com
  - awsdns-32.net
  - awsdns-32.org
  - awsdns-33.co.uk
  - awsdns-33.com
  - awsdns-33.net
  - awsdns-33.org
  - awsdns-34.co.uk
  - awsdns-34.com
  - awsdns-34.net
  - awsdns-34.org
  - awsdns-35.co.uk
  - awsdns-35.com
  - awsdns-35.net
  - awsdns-35.org
  - awsdns-36.co.uk
  - awsdns-36.com
  - awsdns-36.net
  - awsdns-36.org
  - awsdns-37.co.uk
  - awsdns-37.com
  - awsdns-37.net
  - awsdns-37.org
  - awsdns-38.co.uk
  - awsdns-38.com
  - awsdns-38.net
  - awsdns-38.org
  - awsdns-39.co.uk
  - awsdns-39.com
  - awsdns-39.net
  - awsdns-39.org
  - awsdns-40.co.uk
  - awsdns-40.com
  - awsdns-40.net
  - awsdns-40.org
  - awsdns-41.co.uk
  - awsdns-41.com
  - awsdns-41.net
  - awsdns-41.org
  - awsdns-42.co.uk
  - awsdns-42.com
  - awsdns-42.net
  - awsdns-42.org
  - awsdns-43.co.uk
  - awsdns-43.com
  - awsdns-43.net
  - awsdns-43.org
  - awsdns-44.co.uk
  - awsdns-44.com
  - awsdns-44.net
  - awsdns-44.org
  - awsdns-45.co.uk
  - awsdns-45.com
  - awsdns-45.net
  - awsdns-45.org
  - awsdns-46.co.uk
  - awsdns-46.com
  - awsdns-46.net
  - awsdns-46.org
  - awsdns-47.co.uk
  - awsdns-47.com
  - awsdns-47.net
  - awsdns-47.org
  - awsdns-48.co.uk
  - awsdns-48.com
  - awsdns-48.net
  - awsdns-48.org
  - awsdns-49.co.uk
  - awsdns-49.com
  - awsdns-49.net
  - awsdns-49.org
  - awsdns-50.co.uk
  - awsdns-50.com
  - awsdns-50.net
  - awsdns-50.org
  - awsdns-51.co.uk
  - awsdns-51.com
  - awsdns-51.net
  - awsdns-51.org
  - awsdns-52.co.uk
  - awsdns-52.com
  - awsdns-52.net
  - awsdns-52.org
  - awsdns-53.co.uk
  - awsdns-53.com
  - awsdns-53.net
  - awsdns-53.org
  - awsdns-54.co.uk
  - awsdns-54.com
  - awsdns-54.net
  - awsdns-54.org
  - awsdns-55.co.uk
  - awsdns-55.com
  - awsdns-55.net
  - awsdns-55.org
  - awsdns-56.co.uk
  - awsdns-56.com
  - awsdns-56.net
  - awsdns-56.org
  - awsdns-57.co.uk
  - awsdns-57.com
  - awsdns-57.net
  - awsdns-57.org
  - awsdns-58.co.uk
  - awsdns-58.com
  - awsdns-58.net
  - awsdns-58.org
  - awsdns-59.co.uk
  - awsdns-59.com
  - awsdns-59.net
  - awsdns-59.org
  - awsdns-60.co.uk
  - awsdns-60.com
  - awsdns-60.net
  - awsdns-60.org
  - awsdns-61.co.uk
  - awsdns-61.com
  - awsdns-61.net
  - awsdns-61.org
  - awsdns-62.co.uk
  - awsdns-62.com
  - awsdns-62.net
  - awsdns-62.org
  - awsdns-63.co.uk
  - awsdns-63.com
  - awsdns-63.net
  - awsdns-63.org

:thawte: 
  :name: thawte
  :dba: 
  - thawte consulting cc
  - thawte consulting (pty) ltd.
:oneandone: 
  :name: 1 and 1
  :dba: 
  - 1 & 1 internet ag
  - 1and1.com
  - 1&1 internet inc.
:gandi: 
  :name: Gandi SAS
  :dba: 
  - gandi sas
  - gandi.net
  - dns.gandi.net
:digicert: 
  :name: DigiCert
  :dba: 
  - digicert inc
:webfaction: 
  :name: WebFaction
  :dba: 
  - webfaction.com
  - webfaction
:safenames: 
  :name: Safenames
  :dba: 
  - safenames ltd
:mediatemple: 
  :name: Media Temple
  :dba: 
  - media temple, inc.
  - mediatemple.net
:dynadot: 
  :name: Dynadot
  :dba: 
  - dynadot, llc
:aol: 
  :name: AOL
  :dba: 
  - aol transit data network
  - aol, llc
  - aol.com
:pair: 
  :name: pair Networks
  :dba: 
  - pair networks
  - pair.com
:godaddy: 
  :name: Go Daddy
  :dba: 
  - domaincontrol.com
  - godaddy.com
  - godaddy.com, inc.
  - godaddy.com, llc
  - secureserver.net
  - wild west domains, inc.
:dnsmadeeasy: 
  :name: DNS Made Easy
  :dba: 
  - dnsmadeeasy.com
:yahoo: 
  :name: Yahoo!
  :dba: 
  - yahoo.com
  - inktomi corporation
  - altavista company
:savis: 
  :name: Savvis
  :dba: 
  - savvis
  - savvis.net
:melbourneit: 
  :name: Melbourne IT
  :dba: 
  - melbourne it, ltd. d/b/a internet names worldwide
:easydns: 
  :name: easyDNS
  :dba: 
  - easydns technologies, inc.
  - easydns.com
  - easydns.net
  - easydns.org
:att: 
  :name: ATT
  :dba: 
  - at&t enhanced network services
  - at&t internet services
  - att.net
:tucows: 
  :name: Tucows
  :dba: 
  - tucows inc.
  - tucows.com co.
  - 
:pairnic: 
  :name: pairNIC
  :dba: 
  - pairnic
:google: 
  :name: Google
  :dba: 
  - aspmx.l.google.com
  - google.com
  - googlemail.com
  - l.google.com
  - google
  - google inc.
:domaindiscover: 
  :name: DomainDiscover
  :dba: 
  - domaindiscover
  - domaindiscover.com
:ait: 
  :name: AIT
  :dba: 
  - advanced internet technologies, inc.
:serverbeach: 
  :name: ServerBeach
  :dba: 
  - serverbeach
:microsoft: 
  :name: Microsoft
  :dba: 
  - msft.net
  - microsoft.com
  - microsoft corp
:enom: 
  :name: eNom
  :dba: 
  - emailsrvr.com
  - enom, inc.
  - enom, incorporated
  - messagingengine.com
  - name-services.com
  - registrar-servers.com
:comodo: 
  :name: Comodo Group
  :dba: 
  - comodo ca limited
  - the usertrust network
:ultradns: 
  :name: Neustar (UltraDNS)
  :dba: 
  - ultradns.info
  - ultradns.net
  - ultradns.org
  - ultradns.co.uk
:postini: 
  :name: Google (Postini)
  :dba: 
  - psmtp.com
:iac: 
  :name: IAC Search and Media
  :dba: 
  - iac search media inc
:domainpeople: 
  :name: DomainPeople
  :dba: 
  - domainpeople, inc.
:netnames: 
  :name: NetNames
  :dba: 
  - group nbt plc aka netnames
:equifax: 
  :name: Equifax
  :dba: 
  - equifax secure inc.
  - equifax
:csc: 
  :name: Corporation Service Company
  :dba: 
  - csc corporate domains, inc.
:verisign: 
  :name: VeriSign
  :dba: 
  - verisign trust network
  - verisign, inc.
:geotrust:
  :name: GeoTrust
  :dba:
  - geotrust, inc.
:rackspace: 
  :name: Rackspace
  :dba: 
  - rackspace.com
  - rackspace.com, ltd.
  - rackspace hosting
  - stabletransit.com
:slicehost:
  :name: Slicehost
  :dba:
  - slicehost llc
  - slicehost.net
:internap: 
  :name: Internap
  :dba: 
  - pnap.net
  - internap network services corporation
:dotster: 
  :name: Dotster
  :dba: 
  - dotster, inc.
:akami: 
  :name: Akamai
  :dba: 
  - akam.net
  - akamai technologies
  - akamai technologies, inc.
:domainbank:
  :name: Domain Bank
  :dba:
  - dstr acquisition pa i, llc dba domainbank.com
:nettica:
  :name: Nettica
  :dba:
  - nettica.com
  - nettica domains, inc.
:he: 
  :name: Hurricane Electric
  :dba: 
  - hurricane electric, inc.
:dreamhost: 
  :name: DreamHost
  :dba: 
  - new dream network, llc
  - dreamhost.com
:zerigo: 
  :name: Zerigo
  :dba: 
  - zerigo.net
:linode: 
  :name: Linode
  :dba: 
  - linode
  - linode.com
  - global net access, llc
:cloudflare:
  :name: CloudFlare
  :dba:
  - cloudflare.com
  - cloudflare, inc.
:joker:
  :name: Joker.com
  :dba:
  - csl computer service langenbach gmbh d/b/a joker.com
:mailgun:
  :name: Mailgun
  :dba:
  - mailgun.org
:namecom:
  :name: Name.com
  :dba:
  - name.com
  - name.com llc
:moniker:
  :name: Moniker
  :dba:
  - moniker online services, inc.
:blacklotus:
  :name: Black Lotus
  :dba:
  - black lotus communications
:issue:
  :name: DNS issue
  :dba:
  - opendns, llc
